### ISSUE TITLE
Adding files to the plugin classpath

### ISSUE THREAD

**Issue by sergeykad** [liquibase/liquibase-gradle-plugin#10]
It will be more convenient if it will be possible to modify classpath directly from the plugin configuration instead of Gradle _buildscript_ configuration.

The Liquibase plugin requires at least DB connector jar to be added to the classpath and often other jars/files as well and putting them into the general configuration makes configuration less tidy.

**Comment by atomfrede** [comment]
I jump on this old issue here. I would like to[ replace our custom](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/gradle/_liquibase.gradle) `diffChangelog` task in https://github.com/jhipster/generator-jhipster with this plugin to support all other liquibase tasks out of box without custom code. 

So I need to add spring dependencies to the classpath of the plugin. It is not very convinient to add them to the buildscript classpath, so if there would a possibility to add dependencies to the plugin classpath that would be awesome. 

Furthermore putting the diffChangelog into a file would be cool :)

**Comment by stevesaliman** [comment]
Version 2.0.0 of the Liquibase Gradle plugin changed the way the classpath is set for Liquibase, which might fix this issue.  You can now easily add any artifacts you need with `liquibaseRuntime` dependencies inside the normal `dependencies` block of the build.gradle file. 

Does this problem still occur in the 2.0.0 relesae?

**Comment by atomfrede** [comment]
Thanks for the hint. Will try it during the weekend

**Comment by atomfrede** [comment]
@stevesaliman It is done: https://github.com/jhipster/generator-jhipster/pull/8171/files so be prepated for more issues coming in maybe after we have released the change. I will open another issue with some things I found during implementing it.

**Comment by atomfrede** [comment]
@stevesaliman I think we can close this issue.
