### ISSUE TITLE
Upgrade liquibase version

### ISSUE THREAD

**Issue by diegogargaro** [liquibase/liquibase-gradle-plugin#11]
Could you upgrade the liquibase version to the newest one (3.5.1)? It solves some issues like this one for postgres that bothers a lot when we need to drop and create again the db (https://liquibase.jira.com/browse/CORE-2693)

Thank you!

**Comment by stevesaliman** [comment]
As long as version 3.5 doesn't introduce any changes to what can be in a changelog, I should be able to do this over the weekend.

**Comment by stevesaliman** [comment]
It looks like Liquibase 3.5.1 has some problems with the ```sqlFile``` change, whose ```endDelimiter``` attribute appears to be broken.  I don't really want to update the plugin to this version until it is fixed - if for no other reason than it will break the projects we have at my day job :-)

If this is not a problem for you, and you don't need any of the 10 new attributes provided, like ```context``` on an ```include```, then there is a way you can get the existing plugin to use a different version of Liquibase.  Simply edit the build.gradle file and replace:
``` 
classpath 'org.liquibase:liquibase-gradle-plugin:1.2.1'
```
with:
```
classpath('org.liquibase:liquibase-gradle-plugin:1.2.1') {
  exclude group: "org.liquibase", module: "liquibase-core"
}
classpath "org.liquibase:liquibase-core:3.5.1"
```
And the plugin will use Liquibase 3.5.1 to run the change sets.

Development of Liquibase 4.0 is well underway, and I've been reworking the Groovy DSL to work with it.  Hopefully, the Groovy DSL and the Gradle plugin will be able to support Liquibase 4.0 as soon as it comes out.

**Comment by diegogargaro** [comment]
I agree. If it will break other things on this new version is better to wait until a stable one is released.

Thanks for the tip! I use the new attributes but they are not needed for the dropAll task, so I can change the version when I need it.

**Comment by susau** [comment]
Our team definitely needs new plugin with 3.5.2 when 3.5.2 is out.
https://liquibase.jira.com/browse/CORE-2761
https://liquibase.jira.com/browse/CORE-2756
are blocker for us.

**Comment by denisazevedo** [comment]
Hi guys, any news on this upgrade? Thanks

**Comment by stevesaliman** [comment]
The delimiter problem mentioned above still exists in 3.5.3.  I created https://liquibase.jira.com/browse/CORE-2920 to track this issue in the Liquibase core.  Until it gets fixed in Liquibase, users can use 3.5.x versions of Liquibase with the workaround described earlier.

**Comment by krzysztofkominiaksolsoft** [comment]
I have voted for this issue https://liquibase.jira.com/browse/CORE-2920
Maybe others can do the same?

**Comment by newnewcoder** [comment]
I have voted for CORE-2920 too.
Issue [CORE-1897](https://liquibase.jira.com/browse/CORE-1897) happened to me, it's solved in Liquibase 3.5.
It would be nice to have the issue fixed insdead of using workaround.

**Comment by devotional** [comment]
I voted for CORE-2920 as well. I have stumbled into [CORE-2688](https://liquibase.jira.com/browse/CORE-2688) solved in 3.5.0.

**Comment by eximius313** [comment]
Good news: https://liquibase.jira.com/browse/CORE-2920 will be fixed in 3.6.0!

**Comment by stevesaliman** [comment]
That is good news.

I'll start watching for a release, then I can make sure the plugin (or the Groovy DSL under it) still works with the latest release.  Chances are I'll have to make some minor tweaks to support additions and deprecations in the new version of Liquibase

**Comment by stevesaliman** [comment]
Well the good news seems to have faded pretty quickly.  I started testing the plugin with the latest pre-release build of version 3.6.0, and immediately ran into https://liquibase.jira.com/browse/CORE-3159, which appears to prevent Liquibase from being run from Gradle at all.

Not good.

So now I'll be following this new bug to see if there is anything that can be done.  The good news is that I've found the source of the problem and come up with a potential fix, but I'm not sure it is the best fix.

The saga continues :-)

**Comment by eximius313** [comment]
Good luck then! :)

**Comment by stevesaliman** [comment]
Thanks to @litpho, we have a workaround for the classpath problems in CORE-3159.  I'm still working on getting a release out, but until then, you can use version 2.0.0-SNAPSHOT of the plugin to use Liquiabse 3.6.  

The latest version of Liquibase seems to have some logging issues that prevent the changes from being shown as they are run, but for those who need the latest version of Liquibase, this may offer a solution.

**Comment by stevesaliman** [comment]
I've just uploaded the latest 2.0.0-SNAPSHOT releases of the Gradle plugin and the Groovy DSL, which should now fully support parsing Liquibase 3.6.1 changelogs.

I still have some testing to do to make sure the serializers work, I need to update the documentation, and I need to look into workarounds for the logging problem, but I hope to have a final release done soon.  In the meantime, users who need to use versions of Liquibase later than 3.4.2 can use the SNAPSHOT releases to get up and running.

**Comment by stevesaliman** [comment]
Release 2.0.0 is now official!  Liquibase 3.6.1 is now fully supported.

Version 2.0.0 is a breaking change.  I tried to document the changes well, please feel free to submit pull requests if there are ways to make the documentation clearer.

Note that Liquibase itself has some issues with logging and console output, as documented in [CORE-3220](https://liquibase.jira.com/browse/CORE-3220).  Until that gets fixed, you can enable console output by adding `mainClassName 'org.liquibase.gradle.OutputEnablingLiquibaseRunner'` to the `liquibase` block of build.gradle.
