### ISSUE TITLE
With Gradle 7.6.2 and Java 17, Liquibase build throwing 'org.liquibase.gradle.LiquibaseTask' property 'command' is missing an input or output annotation

### ISSUE THREAD

**Issue by ramanjaneyulupathuri** [liquibase/liquibase-gradle-plugin#126]
Hi Team,

We are using gradle liquibase plugin 2.2.0, Gradle 7.6.2 and Java 17,
While we run liquibase:update task below exception is throwing.

**Some problems were found with the configuration of task ':liquibase:update' (type 'LiquibaseTask').
  - In plugin 'org.liquibase.gradle' type 'org.liquibase.gradle.LiquibaseTask' property 'command' is missing an input or output annotation.
   
    Reason: A property without annotation isn't considered during up-to-date checking.
   
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.**

**Comment by owpk** [comment]
same issue

**Comment by eranshpiner** [comment]
Hi Team,

Using 'org.liquibase:liquibase-core:4.2.2' with Gradle 7.6 and Java 17, we encounter similar build issues:

Some problems were found with the configuration of task ':liquibase:update' (type 'LiquibaseTask').

- In plugin 'liquibase' type 'org.liquibase.gradle.LiquibaseTask' property 'command' is missing an input or output annotation.
- In plugin 'liquibase' type 'org.liquibase.gradle.LiquibaseTask' property 'requiresValue' is missing an input or output annotation.

Any advise on how to address this issue would be highly appreciated.

**Comment by pthiruma-pinc** [comment]
Same issue, Any updates on how to fix them?

Some problems were found with the configuration of task ':liquibase:update' (type 'LiquibaseTask').
- In plugin 'liquibase' type 'org.liquibase.gradle.LiquibaseTask' property 'command' is missing an input or output annotation.
   
 Reason: A property without annotation isn't considered during up-to-date checking.
    
Possible solutions:
1. Add an input or output annotation.
2. Mark it as @Internal.
  
Please refer to https://docs.gradle.org/7.6.3/userguide/validation_problems.html#missing_annotation for more details about this problem.

**Comment by stevesaliman** [comment]
Version 3.0.0 of the plugin was released this morning, and completely overhauled how the plugin defines and configures tasks.  Is this still an issue with the new version?

**Comment by ramanjaneyulupathuri** [comment]
Solution provided in new version of liquibase plugin
