### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by eric-creekside** [liquibase/liquibase-gradle-plugin#127]
Sincere question. The last commits were 5 months ago, there are 2 old PRs hanging out with no comments, and I don't see any recent activity in the Issues by any of the project committers. I'm just wondering if this plugin is essentially end-of-life or what. No accusations intended, I just need to know if I should use it for my company and the level of activity matters in that decision.

**Comment by stevesaliman** [comment]
This project (and the liquibase Groovy DSL) are both still maintained, though like many open source efforts, I can only work on it in my spare time.

The Gradle plugin in particular is designed to be a simple wrapper around the Liquibase CLI, so it doesn't generally require a lot of maintenance as long as that CLI remains stable, just the occasional patch to deal with java or Gradle changes.

One thing that I'd like to do, but haven't had time to, is improve the test suite for the plugin.  I could merge code much quicker if I had a good way to make sure a change didn't break anything in older versions of Java/Gradle/Liquibase.

**Comment by eric-creekside** [comment]
Thanks for responding, that's good to hear as I'm embarking on a journey where I will be hitching my company's data migration approach to Liquibase, and were not in a position to convert from Gradle to maven right now.
I have a specific question that might be a feature request, and I'll post that as a separate thread.
