### ISSUE TITLE
Is there a simple way to disable the plugin?

### ISSUE THREAD

**Issue by eric-creekside** [liquibase/liquibase-gradle-plugin#128]
I followed the example in the README of using `project.ext.` properties to define Liquibase activity parameters that can be passed in on the command-line.
Like this:
```
liquibase {
	activities {
		main {
		  changelogFile "src/main/resources/db/liquibase/master-changelog.yml"
		  url project.ext.dbURL
		  username project.ext.dbUser
		  password project.ext.dbPassword
		}
	}
}
```
However, doing that causes Gradle to complain when those parameters are not provided. For example, doing an ordinary build (using `gradlew build`, for example) cause the following:
`Cannot get property 'dbURL' on extra properties extension as it does not exist`

I'm not a Gradle expert, and I tried various ways to make applying the plugin and the `liquibase` block _conditional_, but they all failed for me. In the end, I had to make a separate `.gradle` file just for the Liquibase stuff, which is not ideal as it means having to use the `-b liquibase.gradle` command-line arg whenever we want to execute a Liquibase task.

Is there any way to make the Liquibase stuff conditional? For example, if there is no `dbURL` property, just skip everything Liquibase-related altogether?

**Comment by stevesaliman** [comment]
I'm not sure what ways you tried to make the liquibase conditional, but on our projects we do something like this:
```groovy
if ( project.hasProperty("dbURL") && project.hasProperty("dbUser") && project.hasProperty("dbPassword") ) {
    liquibase {
        activities {
            main {
                changelogFile "src/main/resources/db/liquibase/master-changelog.yml"
                url project.ext.dbURL
                username project.ext.dbUser
                password project.ext.dbPassword
            }
        }
    }
}
```

This won't stop the plugin from being applied, and running liquibase tasks will fail if the properties are not set, but it does allow you to run non-liquibase tasks without having to configure anything.

**Comment by eric-creekside** [comment]
That does work, thanks. I don't remember all the ways I tried to avoid running Liquibase; would have thought this one would have been obvious to me but apparently not :-)
