### ISSUE TITLE
Generate Changelog with defaultSchemaName not possible

### ISSUE THREAD

**Issue by sirius322** [liquibase/liquibase-gradle-plugin#130]
I have updated Liquibase from 4.17.0 to 4.23.1 and the plugin from 2.0.4 to 2.2.0.

Now I have trouble migrating my activity for generating a changelog from an existing schema. Before the update I used the `defaultSchemaName` argument. With the new version a changelog with a dummy changeset is being generated. The current [source code](https://github.com/liquibase/liquibase-gradle-plugin/blob/3338844c8cd9adac6f4bd20b88ba45d447be76a8/src/main/groovy/org/liquibase/gradle/liquibase/command/GenerateChangelogCommand.groovy#L21) states that the liquibase command doesn't take the `default-schema-name` argument. 

However, when used directly `liquibase generate-changelog --help` still lists the argument and works as expected when applied directly.

1. Is this a bug or is there a reason why `defaultSchemaName` is not supported by the Gradle plugin?
2. Is there any workaround? 

Two things that I have tried so far :
- Using the option  `-PliquibaseExtraArguments="default-schema-name=SCHEMANAME"` had no effect
- Replacing `defaultSchemaName` with `schemas` produces a changelog but adds the source schema as a `referencedTableCatalogName` to the `addForeignKeyConstraint` 
(`<addForeignKeyConstraint ... referencedTableCatalogName="SCHEMANAME"/>`). This causes an error when Liquibase Update is run with a different schema/database.

**Comment by stevesaliman** [comment]
At the time I last updated the plugin, Liquibase 4.16.1 was current, and the `default-schema-name` was not part of that release from what I can tell.  It isn't in the source code for Liquibase (hence my comment in the plugin), and it doesn't come back when I do `liquibase generate-changelog --help`.

The solution is to update the plugn again to sync it up with the latest CLI.  If I'm lucky, they only added options and didn't remove any...

**Comment by stevesaliman** [comment]
Version 3.0.0 of the plugin has finally been released, with support for Liquibase 4.24+.  

One of the changes in the new version is that the `liquibaseExtraArguments`  property was removed, and Liquibase properties can now be specified/overridden in an easier way.  In this case, you can spefy `-PliquibaseDefaultSchemaName=SCHEMANAME` to do what you need.

Does this solve your issue?

**Comment by sirius322** [comment]
Yes, it does. Thanks for the support. I will close the issue now.
