### ISSUE TITLE
Liquibase --username argument should be placed after the command

### ISSUE THREAD

**Issue by ZooToby** [liquibase/liquibase-gradle-plugin#138]
For some reason, when the database username is `migrate` and the username is specified before the command, liquibase will return the following error: `Error parsing command line: Expected parameter for option '--username' but found 'migrate'`.

example command which causes error:
```shell
liquibase --username=migrate --password=1234 --url="jdbc:postgresql://localhost:5432/sample" --changelog-file=path/to/changelog.yaml status
``` 

This also appears to affect `--reference-username`, eg:
```shell
liquibase --username=write --password=1234 --url="jdbc:postgresql://localhost:5432/sample" --reference-url="jdbc:postgresql://localhost:5433/sample" --reference-username=local --reference-password=1234 diff
```

I'm not sure why 'migrate' specifically is causing this error, however if the `--username` or `--reference-username` is placed after the command then it runs fine. 

If the first command is changed to this it won't cause errors:
```shell
liquibase --password=1234 --url="jdbc:postgresql://localhost:5432/sample" --changelog-file=path/to/changelog.yaml status --username=migrate
``` 

I'm not sure if this is a documented error but it seems the fix would be to add USERNAME and REFERENCE_USERNAME to the POST_COMMAND_ARGUMENTS array in the [LiquibaseCommand.groovy file](https://github.com/liquibase/liquibase-gradle-plugin/blob/master/src/main/groovy/org/liquibase/gradle/LiquibaseCommand.groovy)

**Comment by stevesaliman** [comment]
I think this was becasue "migrate" used to be a valid liquibase command, so seeing it twice on the command line would likely confuse it.

Version 3.0.0 of the plugin, which was finally released this morning, completely overhauls the way the plugin passes arguments to Liquibase, and all arguments are passed as `--arg=value` pairs now, which should fix this issue.
