### ISSUE TITLE
markNextChangesetRan not filtering by label

### ISSUE THREAD

**Issue by Tylorjg** [liquibase/liquibase-gradle-plugin#144]
When using a more recent version of Liquibase (such as Liquibase v4.26.0) with id `'org.liquibase.gradle' version '2.2.1'`, markNextChangesetRan does not filter by the label.

For example, if there are the following changesets

```
<changeSet id="1" author="tylor" labels="pre">
    <sql>
        SELECT COUNT(*) FROM DATABASECHANGELOG;
    </sql>
</changeSet>
<changeSet id="2" author="tylor" labels="main">
     <sql>
         SELECT COUNT(*) FROM DATABASECHANGELOG;
    </sql>
</changeSet>
<changeSet id="3" author="tylor" labels="main">
    <sql>
        SELECT COUNT(*) FROM DATABASECHANGELOG;
    </sql>
</changeSet>
```

running the `markNextChangesetRan` and spacing the label main, the first changeset with ID 1 is marked as ran instead of the changeset with ID 2.

I have tested with Liquibase CLI and it worked as expected, so it appears to be specific to the Gradle plug-in. I tried both labels and labelfilter and each didn't work. 

`markNextChangesetRanSql` also doesn't take into account the label.

**Comment by stevesaliman** [comment]
Release 2.2.2 includes the fix for this issue.
