### ISSUE TITLE
lbDropAll schema

### ISSUE THREAD

**Issue by lukyer** [liquibase/liquibase-gradle-plugin#15]
Only public schema is flushed using lbDropAll task. Custom schemes stay untouched.
db: PostgreSQL.

**Comment by stevesaliman** [comment]
I know this is a stupid question, but does the user you're using have permission to drop objects in the custom schema?

If so, my hunch is that this problem lies withing Liquibase itself.  The plugin just passes on the requested actions and parameters to it.

**Comment by lukyer** [comment]
Yes permissions are correct. I figured out problem really lies on Liquibase side. Thanks.
