### ISSUE TITLE
issue upgrading to 3.0.1 from 2.2.0

### ISSUE THREAD

**Issue by h-ngo** [liquibase/liquibase-gradle-plugin#158]
Liquibase-gradle-plugin: 3.0.1
liquibase-core: 4.29.2

We encountered this error as soon as we upgraded liquibase-gradle-plugin to 3.0.1

A problem occurred evaluating root project 'abc'.
> liquibase/Scope

the error is pointing to this
apply plugin: 'org.liquibase.gradle'

we can't seem to find any info on the error. Any help would be greatly appreciated.

**Comment by stevesaliman** [comment]
Did you add liquibase to the `buildscript` dependencies in build.gradle?  As of version 3.0.0, liquibase itself needs to be in both the `buildscript` and `liquibaseRuntime` dependencies.  The usage.md file gives details.

**Comment by h-ngo** [comment]
yes. we have these

build.gradle (main)

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.liquibase:liquibase-gradle-plugin:3.0.1"
    }
}

in subproject's build.gradle
apply plugin: 'org.liquibase.gradle'

dependencies {
    liquibaseRuntime "org.liquibase:liquibase-core:4.29.2"
    liquibaseRuntime 'info.picocli:picocli:4.7.5'
    liquibaseRuntime 'org.liquibase:liquibase-groovy-dsl:3.0.2'
    liquibaseRuntime group: 'javax.xml.bind', name: 'jaxb-api', version: '2.3.1'
}

project structure:
abc-app
- build.gradle
- Module A
+++ build.gradle
- Liquibase module
+++ build.gradle

**Comment by h-ngo** [comment]
figured out the issue. need to also add "org.liquibase:liquibase-core:4.29.2" to classpath in buildscript as well. This was mentioned in the doc but in a separated section. a bit confusing.
