### ISSUE TITLE
rollback plugin parameter

### ISSUE THREAD

**Issue by eustimenko** [liquibase/liquibase-gradle-plugin#16]
I'd like to add rollback parameter to liquibase gradle like it is in maven, but I could not understand inside code how plugin process the require values such as username, password and url. Could you help me, please?

**Comment by stevesaliman** [comment]
I'm not quite sure what you are asking. The plugin already supports the rollback task.

If the question is how to use the rollback task, you need to do two things.

1) Add/configure a liquibase block in your ```build.gradle``` file.  If you are already able to do a ```gradle update``` there is nothing else you need to do for rollback.  If not, you need something like this:
```groovy
liquibase {
  activities {
    main {
      changeLogFile 'src/main/db/changelogs.groovy'
      url 'jdbc:mysql://localhost:3306/my_db'
	  username 'myusername'
	  password 'mypassword'
    }
  }
}
```

2) Call gradle with the following: ```gradle rollback -PliquibaseCommandValue=someTag``` where "someTag" is what you are trying to rollback to.

**Comment by eustimenko** [comment]
I'd like use rollback as following:
`<configuration>
          <changeLogFile>src/main/resources/liquibase/db.changelog-master.xml</changeLogFile>
          <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
          <driver>org.postgresql.Driver</driver>
          <url>${database.url}</url>
          <username>${database.username}</username>
          <password>${database.password}</password>
          <rollbackCount>1</rollbackCount>
          <outputFileEncoding>UTF-8</outputFileEncoding>
        </configuration>`
This is maven configuration, i.e. at Gradle it should be
`liquibase {
  activities {
    main {
      changeLogFile 'src/main/db/changelogs.groovy'
      url 'jdbc:mysql://localhost:3306/my_db'
      username 'myusername'
      password 'mypassword'
      rollbackCount 1
    }
  }
}`
`gradle rollback`

**Comment by stevesaliman** [comment]
I think the maven plugin tries to combine a couple of Liquibase rollback type commands into a single command.  In your case, I think ```gradle rollbackCount -PliquibaseCommandValue=1``` should do the trick.

In general, the gradle plugin tries to be a simple pass through to Liquibase itself.  Each command listed at http://www.liquibase.org/documentation/command_line.html becomes a Gradle task.  Commands that take arguments (like rollback or tag) get them from the ```-PliquibaseCommandValue=myvalue```, and parameters are part of the ```liquibase``` block.

The goal is to try and make the plugin easier to use by simply mirroring native Liquibase usage.

**Comment by eustimenko** [comment]
@stevesaliman I like this plugin and would like to make it with some features for myself. Could you, please, help me with it? I need answer how to add parameter to activity that will be used by plugin such as username, url or password?

**Comment by stevesaliman** [comment]
Each parameter to an activity is handled by the ```methodMissing``` method of the org.liquibase.gradle.Activity class.  It basically takes the method that was being called, along with its argument, and adds it to the list of parameters that will get passed to Liquibase itself when it is invoked.  Any method you add to the Activity class would become a valid parameter to an activity.  For example, you could define a method called rollbackCount to handle your use case, but that method would need to figure out how to convert that count into the right Liquibase argument.

**Comment by eustimenko** [comment]
@stevesaliman Thank you.
