### ISSUE TITLE
Running Java/Groovy classes as part of a changeset

### ISSUE THREAD

**Issue by andygoossens** [liquibase/liquibase-gradle-plugin#17]
I am wondering whether it is possible to run a Java/Groovy/... class from the same Gradle module. When I tried it, it was giving me a java.lang.ClassNotFoundException.

Example with a XML changeset:
```
  <changeSet id="something" author="me">
    <customChange class="foo.HelloWorld"/>
  </changeSet>
```

I assume that the class isn't part of the classpath that the plugin uses. Putting the class in an external artifact and then adding a 'classpath' dependency on it becomes more complex than it should be. :-(

**Comment by DKroot** [comment]
I have a Gradle build that runs a custom Java/Groovy class from a custom dependency. So, if your class could run in a build task rather than in a changeset this should work.

**Comment by stevesaliman** [comment]
Another thing that comes to mind is that you might be able to put ```HelloWorld.groovy``` inside your project's ```buildSrc/src/main/groovy/foo``` directory.  Classes in buildSrc shoudl automatically be part of the classpsth.

**Comment by dgeissl** [comment]
But you can not support the crazy classloading provided by the CLI, where you can use wars or even ears to liquibase and it searches their jars etc. right?

As far as i see it today. one has to use the older buildscript plugin syntax and include jars with custom tasks etc. in the buildscript classpath. I even can't seem to find a way to use custom jdbc drivers without that syntax:
```
buildscript {
    repositories {
        flatDir {
           dirs 'libs'
        }
        mavenCentral()
    }
    
    dependencies {
        classpath (
            // liquibase
            [group: 'org.liquibase', name:'liquibase-core', version:'3.5.3'],
            // gradle plugin
            [group: 'org.liquibase', name:'liquibase-gradle-plugin', version:'1.2.4'],
            // jdbc driver
            [group: 'com.ibm.db2', name: 'db2jcc', version: '3.59.81'],
            // our own extensions
            [name: 'liquibase-extensions', version: '1.0-SNAPSHOT']
        )
    }
}
```
did i miss something here?

The Liquibase ant tasks are simply not sufficient but at least i can extend their classpath after taskdefinition.

**Comment by dgeissl** [comment]
Ok it tested a bit, and the classpath of a activity works for jdbc drivers but not for extensions as the extensions will not find the liquibase classes. So it seems extensions need to be attached to the buildscript classpath while jdbc drivers and ears/wars can be given to the activity classpath.

Not sure what can be done about it.

**Comment by stevesaliman** [comment]
Version 2.0.0 of the plugin adds `liquibaseRuntime` dependencies for setting up the classpath that Liquibase will use when it runs.  Does this help solve the issue?  If the custom code is part of the project itself, you can add `liquibaseRuntime sourceSets.main.output` as a dependency.

**Comment by stevesaliman** [comment]
Closed due to inactivity.  If this is still an issue with the latest versions of Liquibase and the plugin, we can always open a new issue.

**Comment by vicmosin** [comment]
> Version 2.0.0 of the plugin adds `liquibaseRuntime` dependencies for setting up the classpath that Liquibase will use when it runs. Does this help solve the issue? If the custom code is part of the project itself, you can add `liquibaseRuntime sourceSets.main.output` as a dependency.

@stevesaliman it seems like I am facing the issue.. could specify what exactly do you mean by "you can add `liquibaseRuntime sourceSets.main.output` as a dependency." ? Add where?
