### ISSUE TITLE
consistent filename value between gradle plugin and liquibase java integration.

### ISSUE THREAD

**Issue by bartosz-bilicki** [liquibase/liquibase-gradle-plugin#18]
I just hit same problem as described in http://stackoverflow.com/questions/36217437/liquibase-changeset-filename-format-differences-between-war-deployment-on-applic

I normally have liquibase integrated with application, running at application startup. Now I decided to use liquibase gradle plugin. Updating DB on application startup is convenient for development, but requires DDL rights for application user (not secure, not suitable for production).

When liquibase is run from application runtime, value of _DATABASECHANGELOG.FILENAME_ is
 _classpath:/changelog/something.xml_

Gradle plugin configured with
```
liquibase {
    activities {
        main {
            ...changeLogFile 'src/main/resources/db.changelog.xml'
```
 generates  _FILENAME_ _src/main/resources/changelog/something.xml_ 

Gradle plugin configured with 
```
 changeLogFile 'db.changelog.xml'
            classpath 'src/main/resources/'
```
generates _FILENAME_ _changelog/something.xml_. That is close do output from java runtime, but not the same.

This causes conflicts, re-runs, etc. I see no way to resolve this. It seems one must stick to one method (liquibase from application runtime, or liquibase from gradle).

Could you improve gradle liquibase plugin to have configurable prefix for filename?
It seems that just addming prefix classpath:/ to generated filename would resolve my issue. Naming fill be consistent between java runtime and gradle plugin.

**Comment by stevesaliman** [comment]
Is there a publicly available project that exhibits this behavior?  I don't have any projects locally that call liquibase on startup. 

The gradle plugin doesn't decide how the filenames show up in the database, so my hunch is that this is in Liquibase itself, but I'd be interested in tracing this through the liquibase groovy dsl to see how it is being asked to load the file during application startup - I might be able to get the plugin to do the same.

**Comment by liemle3893** [comment]
build.gradle:

```groovy
def changeLog = "$projectDir/src/main/resources/db/db.changelog-master.xml"

def getProperties(environment) {
    Properties properties = new Properties()
    File propertiesFile = new File("$projectDir/.environment/${environment}.properties")
    propertiesFile.withInputStream {
        properties.load(it)
    }
    return properties
}

task dbMigration {
    doLast {
        def environment = System.properties['APP_ENV'] ?: 'local'
        println "Migrating ${environment}..."
        def properties = getProperties(environment)

        liquibase {
            activities {
                main {
                    changeLogFile changeLog
                    classpath "$projectDir/src/main/resources/"
                    url properties.jdbcUrl
                    username properties.username
                    password properties.password
                }
            }
        }
    }
}
```

db.changelog-master.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
		xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
	<include file="db/changelog/V_20180429165618__db.changelog-create-short-video-table.xml"/>
	<include file="db/changelog/V_20180429165618__db.changelog-create-video-metadata-table.xml"/>
	<include file="db/changelog/V_20180501121226__db.changelog-create-trigger-after-insert-video.xml"/>
</databaseChangeLog>
```
Structure:
```
        └── resources
            └── db
                ├── changelog
                │   ├── V_20180429165618__db.changelog-create-short-video-table.xml
                │   ├── V_20180429165618__db.changelog-create-video-metadata-table.xml
                │   └── V_20180501121226__db.changelog-create-trigger-after-insert-video.xml
                ├── db.changelog-master.xml
                ├── generator.py
                └── sql
                    ├── V_20180501121226__IncreaseStoredProcedure_1.sql
                    └── V_20180501121226__create_metadata_after_insert_video.sql

```

And then:
```
gradle -DAPP_ENV=development dbMigration dropAll update
```
__NOTE__: 
1. `classpath` is __important__
2. Done use `relativeToChangelogFile`
3. XML/Groovy/ Etc.. doesn't matter, choose one which fit you. XML Fit me well when using IDEA, there're autocompletion.

**Comment by stevesaliman** [comment]
Closed due to inactivity, and the fact that later versions of Liquibase have changed how files are handled.  If this is still an issue with the latest versions of Liquibase and the plugin, we can always open a new issue.
