### ISSUE TITLE
Wrong tasks help

### ISSUE THREAD

**Issue by rumatoest** [liquibase/liquibase-gradle-plugin#2]
In your tasks help there are many mentions of <liquibase.commandValue> but this value is invalid because valid value is <liquibaseCommandValue>

Example 
~~~
lqRollbackCount - Rolls back the last <liquibase.commandValue> change sets.
lqRollbackToDate - Rolls back the database to the state it was in at the <liquibase.commandValue> date/time.
lqTag - Tags the current database state with <liquibase.commandValue> for future rollback
lqUpdateCount - Applies the next <liquibase.commandValue> change sets.
~~~

**Comment by stevesaliman** [comment]
I'm not quite sure what you are trying to point out here.  Can you give more information?

**Comment by rumatoest** [comment]
~~~
gradle tasks
~~~
Output this manual
~~~
rollbackCount - Rolls back the last <liquibase.commandValue> change sets.
~~~


According to manual I should use plugin like this:
~~~
gradle rollbackCount -Pliquibase.commandValue=1
~~~
But it will not work this way! Working example is
~~~
gradle rollbackCount -PliquibaseCommandValue=1
~~~
It happens because "liquibase.commandValue" from ```gradle tasks``` != "liquibaseCommandValue" IRL

**Comment by stevesaliman** [comment]
Thank you for the clarification, I see it now.

I updated the documentation to match what the plugin is actually doing.  Version 1.1.1 of the plugin should show up in the normal repositories and mirrors shortly.

Thank you for pointing this out.
