### ISSUE TITLE
unable to pass rollback parameters to gradle task

### ISSUE THREAD

**Issue by Bahar13** [liquibase/liquibase-gradle-plugin#25]
When trying to pass the rollback parameters to a gradle task as suggested using  -PliquibaseCommandValue, the task fails to find the parameter.

The gradle task is defined as below:

task liquibaseRollback(type: JavaExec) {
    group = "liquibase"
    classpath sourceSets.main.runtimeClasspath
    classpath configurations.liquibase
    main = "liquibase.integration.commandline.Main"

    args "--changeLogFile=" + changeLogFile
    args "--databaseChangeLogTableName=" + databaseChangeLogTableName
    args "--databaseChangeLogLockTableName=" + databaseChangeLogLockTableName
    args "--username=" + username
    args "--password=" + password
    args "--url=" + url
    args "--driver=" + driverClassName
    args "rollbackCount"
}

and trying to add **-PliquibaseCommandValue='1'** as the last line of the code or running this task from command line, like:  **_gradle liquibaseRollback -PliquibaseCommandValue='1'_** is not working.

**Comment by newnewcoder** [comment]
How about use this plugin instead of defining a gradle task by `JavaExec`?

**Comment by stevesaliman** [comment]
@newnewcoder is correct.  By defining your own task, you are not using the plugin.  If your activities in the ```liquibase``` block of your build.gradle are correct, you should be able to execute ```gradle rollbackCount -PliquibaseCommandValue=1``` to rollback one change.
