### ISSUE TITLE
Make it a bit clearer that one can use the Oracle Wallet by setting a few systemProps

### ISSUE THREAD

**Issue by MakotoTheKnight** [liquibase/liquibase-gradle-plugin#27]
This is less of a problem with the plugin and more of an issue with how it's documented.

I'm working on a project which makes use of the Oracle wallet, and we were running into an issue with not being able to connect to the database.

[These instructions](http://forum.liquibase.org/topic/using-oracle-wallet) were a good clue, but they didn't transliterate over to the plugin that well.  Initially I had the properties added in a block inside of the `activity` itself:

    dev {
        changeLogFile 'path/to/changelog.xml'
        url 'jdbc:oracle:thin:@ALIAS'
        parameters += [
            'oracle.net.tns_admin': '/path/to/tns_admin/folder'
            'oracle.net.wallet_location': '/path/to/wallet/folder'
        ]
    }

However that was unnecessary (and also not working).

What I wound up doing was adding these values into the `gradle.properties` file directly:

```
systemProp.oracle.net.tns_admin=/path/to/tns_admin/folder
systemProp.oracle.net.wallet_location=/path/to/wallet/folder
```

While I realize that this quite niche, I feel like this should be documented somewhere.  If I'm told where it's acceptable to do so, I can also write up the documentation in my spare time.

**Comment by stevesaliman** [comment]
Closing due to age.  Oracle Wallet requires certain system properties to be set, and this is done using standard Gradle mechanisms.
