### ISSUE TITLE
Add warning message when plugin isn't configured.

### ISSUE THREAD

**Issue by ghost** [liquibase/liquibase-gradle-plugin#30]
When one applies liquibase plugin, not configures it, and runs "update" task - the console output displays a message "BUILD SUCCESSFUL". 
It could be great if plugin displayed a warning that "plugin has not been configured" instead.

**Comment by lared** [comment]
+1

**Comment by stevesaliman** [comment]
With release 2.1.0, the plugin now throws an exception when there are no activities defined, which happens when the plugin isn't configured.

Better late than never I suppose :-)
