### ISSUE TITLE
Add possibility to use extensions such as liquibase-hibernate5

### ISSUE THREAD

**Issue by kowlown** [liquibase/liquibase-gradle-plugin#33]
It would be great if we could use extension as liquibase-hibernate5 like done for the liquibase-maven-plugin.

We can configure the maven plugin with dependencies like this :
```
<plugins>
    <plugin>
        <groupId>org.liquibase</groupId>
        <artifactId>liquibase-maven-plugin</artifactId>
        <version>3.4.1</version>
        <configuration>                  
            <propertyFile>src/main/resources/liquibase.properties</propertyFile>
        </configuration> 
        <dependencies>
            <dependency>
                <groupId>org.liquibase.ext</groupId>
                <artifactId>liquibase-hibernate4</artifactId>
                <version>3.5</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-beans</artifactId>
                <version>4.1.7.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-jpa</artifactId>
                <version>1.7.3.RELEASE</version>
            </dependency>
        </dependencies>               
    </plugin> 
</plugins>
```

**Comment by stevesaliman** [comment]
I must confess that I've never used liquibase plugins...

What happens when you add ```classpath org.liquibase.ext:liquibase-hibernate5:3.6``` to your ```buildscript``` dependencies?

**Comment by stevesaliman** [comment]
Since my last comment, the way we handle the classpath when we run Liquibase has changed.  Starting with version 2.0 of the plugin, you can use`liquibaseRuntime` dependencies to add artifacts to the classpath when Liquibase runs, and this has been tested with projects that use the exact liquibase-hibernate dependency you are trying to use.

Does that solve your issue?

**Comment by foverzar** [comment]
Adding `liquibaseRuntime 'org.liquibase.ext:liquibase-hibernate5:3.6'` works like charm. Before 2.0 using `classpath` also worked fine. In fact, using `liquibaseRuntime` seems to let you take full advantage of `io.spring.gradle:dependency-management-plugin`

I also had to add `liquibaseRuntime sourceSets.main.output` to avoid this issue: https://github.com/liquibase/liquibase-hibernate/issues/170
