### ISSUE TITLE
relativeToChangelogFile="true" doesn't work inside sqlFile-tag

### ISSUE THREAD

**Issue by RomanShkola** [liquibase/liquibase-gradle-plugin#34]
When I'm trying to execute my changelogs using gradle, there is always the exception thrown:
File doesn't exist. 

```
<sqlFile dbms="postgresql"
            encoding="utf8" 
	    relativeToChangelogFile="true"
            path="/databasePostgreSQL/001_classicaldbstruct/create_tables.sql"/>
<rollback>
```
My Gradle-file:
```
task('dev') << {
	println "executing dev"
	liquibase {
		activities {
	        main {
	        	ext.extProgram = new Properties()
				extProgram.load(new FileInputStream("$projectDir/config/configJenkins/system.properties"))
	            changeLogFile '/src/database/changelog/db.changelog-master.xml'
	            url extProgram['DB_URL']
	            username extProgram['DB_LOGIN']
	            password extProgram['DB_PWD']
	            classpath "$projectDir"
	        }
	    }
		runList = 'main'
	}
}
```

**Comment by stevesaliman** [comment]
I'm not sure what could be happening here.  I have a simple project with a changelog that includes a sql file, and it seems to be working.  Exactly what file is liquibase complaining about?  could there be a typo in the filename?

**Comment by RomanShkola** [comment]
I have the master changelog file where the include-tag is placed (there is also relativeToChangelogFile attribure which works correctly), and it includes the file (let's say 'changelog-sql.xml') which contains the stuff I added above: 
```
  <sqlFile dbms="postgresql"
            encoding="utf8" 
	    relativeToChangelogFile="true"
            path="/databasePostgreSQL/001_classicaldbstruct/create_tables.sql"/>
```
And exactly this changelog-sql.xml causes the error "File doesn't exist".

**Comment by RomanShkola** [comment]
Yes, you underestood everything correctly. 
So, the example that you have added above should work for sure?

**Comment by stevesaliman** [comment]
I have a working example using the files I mentioned in my previous answer came from a working project, though I did remove the xmlns stuff from the databaseChangeLog tag for brevity.

**Comment by RomanShkola** [comment]
The folder structure is the following:
```
+ database
├── + databasePostgreSQL
│   └── ...
├── + changelog
│   └── + PROJECT-X.X.X
│   │   └── ...
│   │   └── db.changelog.xml
│   │   └── db.tag.xml
│   └── db.changelog-master.xml
│   └── db.tag-BASELINE.xml
```

So, as you can see create_tables.sql file is outside the changelog folder. Is it still possible to use relativeToChangelogFile attribute?

**Comment by RomanShkola** [comment]
When I don't use Gradle to run Liquibase, but liquibase command instead, then everything works without relativeToChangelogFile attribute.

**Comment by RomanShkola** [comment]
Ok, I resolved it using the following:
```
<sqlFile dbms="postgresql"
            encoding="utf8" relativeToChangelogFile="true"
            path="../../databasePostgreSQL/001_classicaldbstruct/create_tables.sql"/>
<rollback>
```

**Comment by stevesaliman** [comment]
There is another solution you can use that should work.  It's how I use the plugin with the Groovy DSL, but I'd expect the same behavior with XML.

Gradle is typically run from the project root directory.  If you specify all of your paths relative to the project root, you can skip the ```relativeToChangelogFile``` attribute and files will still be found.  Using my previous example, I could have included my second changelog with a path of ```src/main/db/changelog/master.xml``` and without the ```relativeToChangelogFile```.  The second changelog could include the SQL with a path of ```src/main/db/changelog/sql/check.sql```, again without the ```relativeToChangelogFile```.  

Neither approach is particularly better or worse than the other, just 2 different ways of tackling the same problem.
