### ISSUE TITLE
ClassCastException with Logger

### ISSUE THREAD

**Issue by alexcase52** [liquibase/liquibase-gradle-plugin#36]
Hi,
I experience [this](https://liquibase.jira.com/browse/CORE-3159?attachmentViewMode=gallery) on java 10, linux, liqubase 3.6.1, liquibase-plugin 1.2.4.
Do you have any plans on fixing this? I think the approach there is fine.

**Comment by stevesaliman** [comment]
I don't know what the plan is to fix CORE-3195, but a pull request has been submitted to the Liquibase Gradle plugin that might work around the problem.

I'm hoping to get time over the weekend to look at it.

**Comment by regrog** [comment]
https://liquibase.jira.com/browse/CORE-3159

**Comment by stevesaliman** [comment]
Thanks to @litpho the latest version of the plugin separates the classpath used by Liquibase from the one Gradle itself uses.  I'm still working on getting a final 2.0.0 release out, but until then, I've uploaded the 2.0.0-SNAPSHOT release to the sonatype snapshot repository.

**Comment by stevesaliman** [comment]
I've just uploaded the latest 2.0.0-SNAPSHOT releases of the Gradle plugin and the Groovy DSL, which should now fully support parsing Liquibase 3.6.1 changelogs.

I still have some testing to do to make sure the serializers work, and I need to update the documentation, but I hope to have a final release done soon.  In the meantime, users who need to use versions of Liquibase later than 3.4.2 can use the SNAPSHOT releases to get up and running.

**Comment by stevesaliman** [comment]
Release 2.0.0 is now official!  Liquibase 3.6.1 is now fully supported, and there are no class cast problems when it runs.

However, Liquibase itself has some issues with logging and console output, as documented in [CORE-3220](https://liquibase.jira.com/browse/CORE-3220).  Until that gets fixed, you can enable console output by adding `mainClassName 'org.liquibase.gradle.OutputEnablingLiquibaseRunner'` to the `liquibase` block of build.gradle.  

Version 2.0.0 is a breaking change.  I tried to document the changes well, please feel free to submit pull requests if there are ways to make the documentation clearer.

**Comment by eximius313** [comment]
https://liquibase.jira.com/browse/CORE-3159 is fixed now
