### ISSUE TITLE
Passing variables to liquibase

### ISSUE THREAD

**Issue by alessandro-dibella-rockalltech** [liquibase/liquibase-gradle-plugin#42]
Using the the liquibase maven plugin it is possible to have changesets like:

```sql
--liquibase formatted sql
--changeset rdbms:827d580e-b864-4ce7-ae8e-a0ffa34623d4 dbms:postgresql context:init runInTransaction:false
CREATE DATABASE ${database.name} WITH OWNER=${database.application.role} ENCODING='UTF8';
```

and to pass the values for `database.name` and `database.name` from the pom.xml file.
Is it possible to do something similar using this plugin?

**Comment by litpho** [comment]
From the README:
4. In addition to the command pass-through methods of an activity, there is a changeLogParameters method. This method takes a map, and is used to setup token substitution in the changeLogs. See the Liquibase documentation for more details on token substitution.
