### ISSUE TITLE
Some special properties

### ISSUE THREAD

**Issue by atomfrede** [liquibase/liquibase-gradle-plugin#45]
In jhipster we will have the following activities:

```gradle
project.ext.diffChangelogFile = 'src/main/resources/config/liquibase/changelog/' + new Date().format('yyyyMMddHHmmss') + '_changelog.xml'

liquibase {
    activities {
        main {
            driver 'org.postgresql.Driver'
            url 'jdbc:postgresql://localhost:5432/liquibasepostgres'
            username 'liquibasepostgres'
            password ''
            changeLogFile 'src/main/resources/config/liquibase/master.xml'
            defaultSchemaName ''
            logLevel 'debug'
            classpath 'src/main/resources/'
        }
        diffLog {
            driver 'org.postgresql.Driver'
            url 'jdbc:postgresql://localhost:5432/liquibasepostgres'
            username 'liquibasepostgres'
            password ''
            changeLogFile project.ext.diffChangelogFile
            referenceUrl 'hibernate:spring:com.mycompany.myapp.domain?dialect=org.hibernate.dialect.PostgreSQL82Dialect&amp;hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&amp;hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy'
            defaultSchemaName ''
            logLevel 'debug'
            classpath 'src/main/resources/'
            excludeObjects 'oauth_access_token, oauth_approvals, oauth_client_details, oauth_client_token, oauth_code, oauth_refresh_token'
        }
    }

    runList = project.ext.runList
}
```

It would be cool have e.g. a special property `diffChangelogFile` (like in the maven plugin) such that there could be one activity. Furthermore adding the `excludeObjects` property to an activity and executing e.g. `liquibaseValidate` the execution will fail as `excludeObjects` is not allowed for non `diff` commands. I don't know how the maven plugin is doing it, but I guess they are looking the command to execute it and only forward the arguments that are supported by the command to the cli. I could try a PR if you also think thats a valid feature request.

**Comment by stevesaliman** [comment]
The Liquibase Maven plugin appears to have a different source file for each target the plugin supports.  Each target can then do whatever it wants to do before invoking Liquibase itself.  It is worth noting that the Maven plugin is part of the core Liquibase repository, and maintained by the same person.

The Gradle plugin took a different approach.  My goal was to have the plugin be a thin wrapper around the command line execution of Liquibase.  I wanted to simply pass through any elements of an activity to Liquiabse with as little processing as possible.  If Liquibase ever adds or changes command line options, users could simply fix their build.gradle files.  No plugin release would be required.

I don't think having 2 different activities is that ugly - one activity is used for changing a single database, and the second involves multiple databases.  The property duplication can be minimized by using Gradle properties, like your example does with the changeLogFile.

I'm not completely opposed to adding this, but I want to minimize the amount of work that would need to be done, and the number of things that need to be checked when new versions of Liquibase are released.

**Comment by atomfrede** [comment]
Makes totally sense what you say. It is not that ugly but at first I found it quite confusing if you configure e.g. `excludeObjects` the execution will fail for certain liquibase commands that don't support it. So I am ok to with the current approach and of course there is still some optimization possible on our side. So lets close it and maybe revisit it if needed.
