### ISSUE TITLE
allow to configure databaseChangeLogTableName and databaseChangeLogLockTableName

### ISSUE THREAD

**Issue by tompson** [liquibase/liquibase-gradle-plugin#5]
for example to prefix them with a special namespace

**Comment by stevesaliman** [comment]
You can already configure these things with the plugin.  There was some discussion of this in the old repo (https://github.com/tlberglund/gradle-liquibase-plugin/issues/28).  Is your request something different?

**Comment by tompson** [comment]
I looked at that thread and I tried to configure it via

```gradle -Dliquibase.databaseChangeLogTableName=WMS_DBCHANGELOG updateSQL```

or by adding 

```System.setProperty('liquibase.databaseChangeLogTableName', "WMS_DBCHANGELOG")```

to my build.gradle file but it did not have any effect

**Comment by tompson** [comment]
thanks for that hint, setting it via 

```System.setProperty('liquibase.databaseChangeLogTableName', "DBCHANGELOG")```

does exactly what I need!
