### ISSUE TITLE
Plugin doesn't find changelog.yml with liquibase-core version 4.0.0

### ISSUE THREAD

**Issue by rackdon** [liquibase/liquibase-gradle-plugin#77]
I can execute migrations correctly with the liquibase-core version 3.10.1, but if I update that version the 4.0.0 I receive the error that changelog.yml does not exist

**Comment by kiranm516** [comment]
@rackdon I'm able to execute migrations using YAML (only single change log file)
Are you using any include?

As per liquibase release notes (https://github.com/liquibase/liquibase/releases/tag/v4.0.0-beta1), it says there are changes to "How Liquibase Finds Files". But, I'm not sure about the exact changes.

It might be some path/config related issue.

**Comment by stevesaliman** [comment]
The biggest change to `include` is that absolute paths are no longer supported.  You should be able to add `--classpath=/` to the run, and have it work, but I haven't tried it.  It is probably better to change absolute paths that are either relative to the working directory or to the changelog file itself.  The good news is that making that change won't affect the checksums on any of your change sets, so it is a safe change to make.

**Comment by rackdon** [comment]
That was the problem, thank you very much
