### ISSUE TITLE
No plugin support for passing any "contexts" argument through to liquibase

### ISSUE THREAD

**Issue by scrain** [liquibase/liquibase-gradle-plugin#8]
Does not appear to be any easy way to pass "contexts" through to liquibase using the plugin.  I've implemented something similar to what is found [here](http://stackoverflow.com/questions/33882138/gradle-liquibase-plugin-not-using-specified-contexts) but  it seems like it should be more directly supported.  

Happy to help with a pull request, but would like to know if a) if there is agreement this should be addressed... and b) what the suggested approach might be.

Thanks

**Comment by DKroot** [comment]
We do this fine in our projects. I have to say we're still on 3.2, but plan to upgrade to the latest version soon.
```
liquibase {
    activities {
        def liquibaseScript = 'sql/Release-Migration/Release-Delta.xml'
        if (file(liquibaseScript).exists()) {
            main {
                changeLogFile liquibaseScript
                url db
                username dbUser
                password dbPwd
                //driver 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
                contexts env
                // changeLogParameters([ myToken: 'myvalue', second: 'secondValue'])

                // Failed SQL is logged on DEBUG level.
                logLevel 'debug'
            }
        }
    }
}
```

**Comment by stevesaliman** [comment]
Thanks for the assist @DKroot.

@scrain All of the methods inside an activity block are simply passed on to Liquibase as if they were specified on the command line.  So in the above example, the ```username dbUser``` method is the same as ```--username=dbUser``` etc.  I've updated the documentation to hopefully avoid future confusion.

**Comment by scrain** [comment]
Thanks for the insight and quick response.
