### ISSUE TITLE
LiquibasePlugin configures 36 tasks eagerly

### ISSUE THREAD

**Issue by runningcode** [liquibase/liquibase-gradle-plugin#87]
[The liquibase configures 36 tasks eagerly](https://ge.jhipster.tech/s/f5dwext7hvonu/performance/configuration?details=code-unit-liquibase!:&openScriptsAndPlugins=WyJjb2RlLXVuaXQtaW8uc3ByaW5nLm5vaHR0cC5ncmFkbGUubm9odHRwY2hlY2tzdHlsZXBsdWdpbiIsImNvZGUtdW5pdC1saXF1aWJhc2UiXQ)

This is on this line: https://github.com/liquibase/liquibase-gradle-plugin/blob/master/src/main/groovy/org/liquibase/gradle/LiquibasePlugin.groovy#L114

[Here you can see the APIs to avoid and their replacements](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) in order to take advantage of task configuration avoidance.

**Comment by stevesaliman** [comment]
Version 2.1.0 uses Gradle's task configuration avoidance API, which should fix this issue.
