### ISSUE TITLE
Add Liquibase 4.5 checks commands

### ISSUE THREAD

**Issue by andrew-simmons** [liquibase/liquibase-gradle-plugin#92]
Liquibase 4.5 added Qualify Checks commands.

Would like to be able to run checks. Other commands could be helpful too.

**Comment by stevesaliman** [comment]
The 2.1.0 version of the plugin supports Liquibase 4.4 and 4.5.  You can run checks with a command like `gradle checks -PliquibaseCommandValue=run`.

Liquibase will require `info.picocli:picocli:4.6.1` in the liquibaseRuntime classpath, and checks didn't work for me without snakeyaml.
