### ISSUE TITLE
Update task not working after upgrade to version 2.1.0

### ISSUE THREAD

**Issue by dmoidl** [liquibase/liquibase-gradle-plugin#95]
Hi 👋 

After we upgraded the Liquibase Gradle plugin to version 2.1.0 (and found a workaround for [this issue](https://github.com/liquibase/liquibase-gradle-plugin/issues/94)), the update task started failing with:
```
Execution failed for task ':update'.
> Process 'command '/usr/local/Cellar/openjdk@11/11.0.12/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```
which is not very informative. Running the task with the `--info` switch reveals the cause to be
```
Error: Unable to initialize main class liquibase.integration.commandline.LiquibaseCommandLine
Caused by: java.lang.NoClassDefFoundError: picocli/CommandLine$Model$ArgSpec
```

I have no idea how to fix this, but it seems to be related to the new [command line parser](https://github.com/liquibase/liquibase-gradle-plugin/blob/master/src/main/groovy/org/liquibase/gradle/LiquibaseTask.groovy#L200) being used in version `4.4+`.

I was not able to find any solution to this other than downgrading the plugin version back to `2.0.4`.

**Comment by stevesaliman** [comment]
Did you add picocli to the liquibaseRuntime dependencies?  Liquibase 4.4+ needs it, but doesn't include it as a transitive dependency.  `liquibaseRuntime 'info.picocli:picocli:4.6.1'` should do the trick.

**Comment by dmoidl** [comment]
And it did the trick indeed. Thank you, I couldn't find this information anywhere 🙂
